services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: meteora-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    restart: "unless-stopped"
    environment:
      VITE_API_BASE_URL: http://localhost:3333/api